
services:
  helios:
    image: aldmbmtl/helios:latest
    hostname: "helios"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helios
    volumes:
      - /dev/dri:/dev/dri
      - .out/:/mnt/
    environment:
      - USER=helios
      - UID=5040
      - PASSWORD=password
#      - PREFIX=/custom/prefix
    ports:
      - "3000:3000"
