name: Bumpversion

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: What to bump by.
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  Bumpversion:
    runs-on:
      - STANDARD-RUNNER
    container: python:3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure User
        shell: bash
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bumpversion
        shell: bash
        run: |
          pip install bump-my-version
          bump-my-version bump ${{ inputs.bump }} -v

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          push_only_tags: true
          atomic: false
          force: true
